//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.12.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Grammar.g4 by ANTLR 4.12.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="GrammarParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.12.0")]
[System.CLSCompliant(false)]
public interface IGrammarListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] GrammarParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] GrammarParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.declarations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarations([NotNull] GrammarParser.DeclarationsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.declarations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarations([NotNull] GrammarParser.DeclarationsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaration([NotNull] GrammarParser.DeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaration([NotNull] GrammarParser.DeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] GrammarParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] GrammarParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.sum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSum([NotNull] GrammarParser.SumContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.sum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSum([NotNull] GrammarParser.SumContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.average"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAverage([NotNull] GrammarParser.AverageContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.average"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAverage([NotNull] GrammarParser.AverageContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.min"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMin([NotNull] GrammarParser.MinContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.min"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMin([NotNull] GrammarParser.MinContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.max"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMax([NotNull] GrammarParser.MaxContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.max"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMax([NotNull] GrammarParser.MaxContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.count"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCount([NotNull] GrammarParser.CountContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.count"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCount([NotNull] GrammarParser.CountContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.controlstructure"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterControlstructure([NotNull] GrammarParser.ControlstructureContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.controlstructure"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitControlstructure([NotNull] GrammarParser.ControlstructureContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.ifstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfstmt([NotNull] GrammarParser.IfstmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.ifstmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfstmt([NotNull] GrammarParser.IfstmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.whilestmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhilestmt([NotNull] GrammarParser.WhilestmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.whilestmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhilestmt([NotNull] GrammarParser.WhilestmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar([NotNull] GrammarParser.VarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar([NotNull] GrammarParser.VarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.num"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNum([NotNull] GrammarParser.NumContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.num"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNum([NotNull] GrammarParser.NumContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString([NotNull] GrammarParser.StringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString([NotNull] GrammarParser.StringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterText([NotNull] GrammarParser.TextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitText([NotNull] GrammarParser.TextContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.numbers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumbers([NotNull] GrammarParser.NumbersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.numbers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumbers([NotNull] GrammarParser.NumbersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.numberswithoutzero"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumberswithoutzero([NotNull] GrammarParser.NumberswithoutzeroContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.numberswithoutzero"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumberswithoutzero([NotNull] GrammarParser.NumberswithoutzeroContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperator([NotNull] GrammarParser.OperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperator([NotNull] GrammarParser.OperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.bool"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBool([NotNull] GrammarParser.BoolContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.bool"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBool([NotNull] GrammarParser.BoolContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.upperCaseLetters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUpperCaseLetters([NotNull] GrammarParser.UpperCaseLettersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.upperCaseLetters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUpperCaseLetters([NotNull] GrammarParser.UpperCaseLettersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.lowercaseLetters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLowercaseLetters([NotNull] GrammarParser.LowercaseLettersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.lowercaseLetters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLowercaseLetters([NotNull] GrammarParser.LowercaseLettersContext context);
}
