//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.12.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Grammar.g4 by ANTLR 4.12.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IGrammarListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.12.0")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class GrammarBaseListener : IGrammarListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] GrammarParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] GrammarParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.declarations"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclarations([NotNull] GrammarParser.DeclarationsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.declarations"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclarations([NotNull] GrammarParser.DeclarationsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaration([NotNull] GrammarParser.DeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaration([NotNull] GrammarParser.DeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] GrammarParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] GrammarParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.sum"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSum([NotNull] GrammarParser.SumContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.sum"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSum([NotNull] GrammarParser.SumContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.average"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAverage([NotNull] GrammarParser.AverageContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.average"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAverage([NotNull] GrammarParser.AverageContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.min"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMin([NotNull] GrammarParser.MinContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.min"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMin([NotNull] GrammarParser.MinContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.max"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMax([NotNull] GrammarParser.MaxContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.max"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMax([NotNull] GrammarParser.MaxContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.count"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCount([NotNull] GrammarParser.CountContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.count"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCount([NotNull] GrammarParser.CountContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.controlstructure"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterControlstructure([NotNull] GrammarParser.ControlstructureContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.controlstructure"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitControlstructure([NotNull] GrammarParser.ControlstructureContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.ifstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfstmt([NotNull] GrammarParser.IfstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.ifstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfstmt([NotNull] GrammarParser.IfstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.whilestmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhilestmt([NotNull] GrammarParser.WhilestmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.whilestmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhilestmt([NotNull] GrammarParser.WhilestmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.var"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar([NotNull] GrammarParser.VarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.var"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar([NotNull] GrammarParser.VarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.num"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNum([NotNull] GrammarParser.NumContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.num"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNum([NotNull] GrammarParser.NumContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString([NotNull] GrammarParser.StringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString([NotNull] GrammarParser.StringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.text"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterText([NotNull] GrammarParser.TextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.text"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitText([NotNull] GrammarParser.TextContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.numbers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumbers([NotNull] GrammarParser.NumbersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.numbers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumbers([NotNull] GrammarParser.NumbersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.numberswithoutzero"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumberswithoutzero([NotNull] GrammarParser.NumberswithoutzeroContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.numberswithoutzero"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumberswithoutzero([NotNull] GrammarParser.NumberswithoutzeroContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperator([NotNull] GrammarParser.OperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperator([NotNull] GrammarParser.OperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.bool"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBool([NotNull] GrammarParser.BoolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.bool"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBool([NotNull] GrammarParser.BoolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.upperCaseLetters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUpperCaseLetters([NotNull] GrammarParser.UpperCaseLettersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.upperCaseLetters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUpperCaseLetters([NotNull] GrammarParser.UpperCaseLettersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.lowercaseLetters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLowercaseLetters([NotNull] GrammarParser.LowercaseLettersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.lowercaseLetters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLowercaseLetters([NotNull] GrammarParser.LowercaseLettersContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
